
******************** COURSERA SCHEMA ***********************************

CREATE SCHEMA COURSERAINTEGRATION_SCHEMA AUTHORIZATION ROOT;

DROP SCHEMA IF EXISTS COURSERAINTEGRATION_SCHEMA;

******************** PROGRAM API TABLE ***********************************

DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.PROGRAM;

CREATE TABLE  COURSERAINTEGRATION_SCHEMA.PROGRAM (
CONTENT_ID VARCHAR(255),
TITLE VARCHAR(255) NOT NULL,
PROVIDER_ID VARCHAR(255) NOT NULL,
STATUS VARCHAR(20),
LAUNCH_URL VARCHAR(255),
ID VARCHAR(255) NOT NULL,
THUMBNAIL_URI VARCHAR(255),
CREATED_DATE DATE,
PRIMARY KEY (ID)
);

******************** CONTENT API TABLE ***********************************

DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.CONTENT;

CREATE TABLE COURSERAINTEGRATION_SCHEMA.CONTENT(
CONTENT_ID VARCHAR(255),
TITLE VARCHAR(255) NOT NULL,
PROVIDER_ID VARCHAR(255) NOT NULL,
STATUS VARCHAR(20),
DESCRIPTION TEXT NOT NULL,
LAUNCH_URL VARCHAR(255),
PROGRAM_ID VARCHAR(255) NOT NULL,
THUMBNAIL_URI VARCHAR(255),
CREATED_DATE DATE,
PRIMARY KEY (CONTENT_ID)
);

******************** CONFIG TABLE ***********************************


DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.CONFIG;

CREATE TABLE COURSERAINTEGRATION_SCHEMA.CONFIG(
CLIENT_ORG_ID SERIAL PRIMARY KEY,
CLIENT_ORG_NAME VARCHAR(255) NOT NULL,
COURSERA_API_CLIENT_SECRET  VARCHAR(255) NOT NULL ,
COURSERA_API_CLIENT_ID VARCHAR(255) NOT NULL ,
LMS_API_CLIENT_SECRET  VARCHAR(255) NOT NULL ,
LMS_API_CLIENT_ID VARCHAR(255) NOT NULL ,
COURSERA_CONTACT_PERSON VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PHONE NUMERIC NOT NULL,
COURSERA_API_HOST VARCHAR(255) NOT NULL
LMS_API_HOST VARCHAR(255) NOT NULL ,
FTP_HOST VARCHAR(255) NOT NULL,
FTP_USER VARCHAR(255) NOT NULL,
FTP_PASSWORD VARCHAR(255) NOT NULL);

******************** BATCHJOBSCHEDULER TABLE ***********************************

DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.BATCH_JOB_SCHEDULER;

CREATE TABLE COURSERAINTEGRATION_SCHEMA.BATCH_JOB_SCHEDULER(
JOB_ID SERIAL PRIMARY KEY,
JOB1_SCHEDULE VARCHAR(255),
JOB2_SCHEDULE VARCHAR(255),
JOB3_SCHEDULE VARCHAR(255),
JOB4_SCHEDULE VARCHAR(255),
JOB5_SCHEDULE VARCHAR(255),
JOB6_SCHEDULE VARCHAR(255),
CLIENT_ORG_ID INTEGER REFERENCES COURSERAINTEGRATION_SCHEMA.CONFIG(CLIENT_ORG_ID),
PRIMARY KEY (JOB_ID));


******************** BATCHJOBDM TABLE ***********************************

DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.BATCH_JOB_DM;

CREATE TABLE COURSERAINTEGRATION_SCHEMA.BATCH_JOB_DM(
JOB_ID SERIAL PRIMARY KEY,
JOB_NAME VARCHAR(255),
DESCRIPTION VARCHAR(255),
PRIMARY KEY (JOB_ID));

******************** STATUS TABLE ***********************************

DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.STATUS;

CREATE TABLE COURSERAINTEGRATION_SCHEMA.STATUS(
USERID VARCHAR(255) NOT NULL ,
ID  VARCHAR(255) NOT NULL ,
PROVIDER_ID VARCHAR(255) NOT NULL,
ISCOMPLETED BOOLEAN ,
COMPLETEDAT DATE ,
GRADE VARCHAR(255));

******************** USER TABLE ***********************************

DROP TABLE IF EXISTS COURSERAINTEGRATION_SCHEMA.USER;

CREATE TABLE COURSERAINTEGRATION_SCHEMA.USER(
ID  VARCHAR(255) NOT NULL ,
EMAIL_ID VARCHAR(255),
EXTERNAL_ID VARCHAR(255) ,
FULL_NAME VARCHAR(255) ,
PRIMARY KEY (ID));


